/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_LmpPair */

#ifndef _Included_jse_lmp_LmpPlugin_LmpPair
#define _Included_jse_lmp_LmpPlugin_LmpPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    neighborRequestDefault_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_neighborRequestDefault_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    neighborRequestFull_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_neighborRequestFull_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    evInit_
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_evInit_1
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    atomX_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_atomX_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    atomF_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_atomF_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    atomType_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_atomType_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    atomNlocal_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_atomNlocal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    forceSpecialLj_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_forceSpecialLj_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    forceNewtonPair_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_forceNewtonPair_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    listInum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_listInum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    listIlist_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_listIlist_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    listNumneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_listNumneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    listFirstneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_listFirstneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    cutsq_
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_cutsq_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    evTally_
 * Signature: (JIIIZDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_evTally_1
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    vflagFdotr_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_vflagFdotr_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_LmpPair
 * Method:    virialFdotrCompute_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024LmpPair_virialFdotrCompute_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
