/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtool_lmp_NativeLmp */

#ifndef _Included_jtool_lmp_NativeLmp
#define _Included_jtool_lmp_NativeLmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtool_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_jtool_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2JJ
  (JNIEnv *, jclass, jobjectArray, jlong, jlong);

/*
 * Class:     jtool_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_jtool_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2J
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     jtool_lmp_NativeLmp
 * Method:    lammpsVersion_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jtool_lmp_NativeLmp_lammpsVersion_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jtool_lmp_NativeLmp
 * Method:    lammpsClose_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jtool_lmp_NativeLmp_lammpsClose_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
