/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_nn_TorchPointer */

#ifndef _Included_jsex_nnap_nn_TorchPointer
#define _Included_jsex_nnap_nn_TorchPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_nn_TorchPointer
 * Method:    dispose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_nn_TorchPointer_dispose0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
