/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_NNAP */

#ifndef _Included_jsex_nnap_NNAP
#define _Included_jsex_nnap_NNAP
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_NNAP_VERSION
#define jsex_nnap_NNAP_VERSION 4L
/*
 * Class:     jsex_nnap_NNAP
 * Method:    forceDot1
 * Signature: ([DII[D[D[D[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_forceDot1
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
