/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_Dlfcn */

#ifndef _Included_jse_clib_Dlfcn
#define _Included_jse_clib_Dlfcn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_Dlfcn
 * Method:    dlopen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_clib_Dlfcn_dlopen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
