/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_CudaNeighborListGetter */

#ifndef _Included_jse_gpu_CudaNeighborListGetter
#define _Included_jse_gpu_CudaNeighborListGetter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    buildCells0
 * Signature: (IIIZFFFFFFFFFFFFJJJIIIJJJJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_buildCells0
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jlong, jlong, jint, jint, jint, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    buildNl0
 * Signature: (IIZFFFFFFFFFFFFJJJIIIJJFJJIJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_buildNl0
  (JNIEnv *, jclass, jint, jint, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jlong, jlong, jint, jint, jint, jlong, jlong, jfloat, jlong, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
