/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_CudaNeighborListGetter */

#ifndef _Included_jse_gpu_CudaNeighborListGetter
#define _Included_jse_gpu_CudaNeighborListGetter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    build0
 * Signature: (IIJJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaNeighborListGetter_build0
  (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
