/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Mirror */

#ifndef _Included_jsex_nnap_basis_Mirror
#define _Included_jsex_nnap_basis_Mirror
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_basis_Mirror
 * Method:    buildNlType1
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Mirror_buildNlType1
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
