/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Basis */

#ifndef _Included_jsex_nnap_basis_Basis
#define _Included_jsex_nnap_basis_Basis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_basis_Basis
 * Method:    forceDot1
 * Signature: ([DIIJJJ[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Basis_forceDot1
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jlong, jlong, jlong, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
