/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Chebyshev */

#ifndef _Included_jsex_nnap_basis_Chebyshev
#define _Included_jsex_nnap_basis_Chebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_Chebyshev_WTYPE_NONE
#define jsex_nnap_basis_Chebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_SINGLE
#define jsex_nnap_basis_Chebyshev_WTYPE_SINGLE 1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FULL
#define jsex_nnap_basis_Chebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_Chebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_Chebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_Chebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_Chebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    eval0
 * Signature: (JJJJIJJIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_eval0
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jlong, jint, jdouble, jint, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalPartial0
 * Signature: (JJJJIJJJJJJIIJJJIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalPartial0
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong, jint, jint, jlong, jlong, jlong, jint, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
