/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_SphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_SphericalChebyshev
#define _Included_jsex_nnap_basis_SphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX 6L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    eval1
 * Signature: ([D[D[D[II[D[D[D[DIDIIIZ)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_eval1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jint, jboolean);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalPartial1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[DIDIIIZ)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalPartial1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
